language: perl
addons:
  apt:
    packages:
      - swig
perl:
  - "5.36"
  - "5.26"
  - "5.10"
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install --deps
script:
  - perl Makefile.PL
  - make
  - make test
